name: Build and Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12.x, 14.x, 15.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Build and package
        run: npm run make

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/make/*
          tag_name: ${{ github.event.inputs.tag }}
